
---
# is intended only for use on Minikube! 
kind: PersistentVolume
apiVersion: v1
metadata:
  name: host-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
